### ISSUE TITLE
Replicate includeCssFile & includeJsFile tag functionality

### ISSUE THREAD

**Issue by chasegiunta** [focuslabllc/craftcms-cachebuster#2]
Would be great to use something along the lines of `{% cacheBuster ('page-specific-styles.css') %}` with optional `first` parameter, like we can with the `includeCssFile` tag.

Spent a ridiculous amount of time setting up my asset revving with gulp to work perfectly, then realized I couldn't replicate the `{% includeCssFile %}` functionality which we're using throughout the project. Totally my fault, let it slip past me. But would definitely be nice to have!

**Comment by erikreagan** [comment]
@ChaseGiunta can you be more specific regarding the functionality you're trying to replicate? I'm unfamiliar with using `includeCssFile`. Maybe you can point me to some docs?

**Comment by chasegiunta** [comment]
Sure! 
https://craftcms.com/docs/templating/includecssfile
https://craftcms.com/docs/templating/includejsfile

Said in the docs but:

> A `<link>` tag that points to your CSS file will be output by the getHeadHtml() function. If you aren’t calling that function anywhere, Craft will insert it right before the HTML’s `</head>` tag.

**Comment by chasegiunta** [comment]
Hopefully it would be easy to piggy back off the way P&T is doing it ...?
https://github.com/pixelandtonic/Craft-Release/blob/master/app/services/TemplatesService.php#L433

**Comment by erikreagan** [comment]
Thanks! Two things:
1. That's pretty cool :)
2. I still don't understand what you're aiming to do. :(

Can you maybe give me an in-context code snippet of how you'd love this to work within a template? Maybe that'll help paint the picture for me.

**Comment by chasegiunta** [comment]
Sure. So, there's kinda two methods to handle page-specific assets. We're not concatenating all of our assets for some particular reason.

In this current project, we don't have a specific block to inherit page-specific assets like shown here. Just because don't need it, really.

**_layout.twig**

```
<html>
  <head>
    {% block head %}{% endblock %}
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>
```

**somepage.twig**

```
{% block head %}
  <link rel='stylesheet' src='public/assets/css/somePageStyles.css'>
{% endblock %}

{% block content %}
  some page content
{% endblock %}
```

---

Instead, our `_layout.twig` looks more like this.

```
<html>
  <head>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

{% includeCssFile '/assets/css/bootstrap.css' first %}
{% includeJsFile '/assets/js/jquery.js' first %}
{% includeJsFile '/assets/js/bootstrap.js' %}
```

and child templates look like so

```
{% block content %}
  some page content
{% endblock %}

{% includeCssFile 'public/assets/css/somePageStyles.css' %}
{% includeJsFile 'public/assets/js/somePageScripts.js' %}
```

We'd like to rev these files ^^^ .
Ideally, something like:
`{% cacheBusterCss ('somePageStyles.css') %}` and it would automatically generate & place our
`<link rel='stylesheet' src='public/assets/css/somePageStyles-123451235.css'>` before our closing `</head>`.

`{% cacheBusterJs ('somePageScripts.js') %}` would do something similar, though automatically placing the script before our closing `</body>`.

Hopefully I'm making sense here! :)

**Comment by erikreagan** [comment]
That's _very_ helpful. Thanks!

What about just using the `cacheBuster` function within the `includeCssFile` argument? It should parse the `cacheBuster` stuff first and then Craft can just do what it's already doing with the results. 

``` twig
{% includeCssFile cacheBuster('/assets/css/bootstrap.css') first %}
{% includeJsFile cacheBuster('/assets/js/jquery.js') first %}
{% includeJsFile cacheBuster('/assets/js/bootstrap.js') %}
```

If you're using the asset manifest approach this should work—in theory. Let me know. :)

**Comment by erikreagan** [comment]
@ChaseGiunta Per our conversation in the Craft Slack yesterday, would you say this particular issue could be considered resolved?

**Comment by chasegiunta** [comment]
Yup! Turns out this was working _exactly_ how we hoped. There were some other issues going on that prevented it working for me initially.
