### ISSUE TITLE
Plugin doesn't seem to work when serving a site with Valet

### ISSUE THREAD

**Issue by wjthomas9** [focuslabllc/craftcms-cachebuster#3]
Trying to figure out what I could be doing wrong with such a simple plugin, but I can't seem to get this plugin to work for me.

Plugin is installed ok.

When I try to use it, it doesn't add the query. Using `{{ 'assets/css/mycssfile.css' | cacheBuster }}` simply outputs the following:

```<link rel="stylesheet" href="assets/css/mycssfile.css" />```

So, then I tried adding the custom query, just to see if the plugin was being triggered at all. When I use `cacheBuster('bustIt=')`, I get the following output.

```<link rel="stylesheet" href="bustIt=/assets/css/mycssfile.css" />```

¯\_(ツ)_/¯

**Comment by wjthomas9** [comment]
Hmmm, appears to work on my staging site. Does the plugin ignore local dev?

**Comment by erikreagan** [comment]
Are any errors being logged? You can find the Cache Buster log file in craft/storage/runtime/logs/cachebuster.log or by viewing it in the Admin
area at /admin/utils/logs/cachebuster.log.

**Comment by erikreagan** [comment]
Nope, no environmental exceptions are built in.

**Comment by wjthomas9** [comment]
No plugin log file, so I don't think it's generating any errors. Strange. Oh well, I may try it on another local dev site as well to see if I can replicate the issue on localhost. Feel free to close this if you want.

**Comment by erikreagan** [comment]
It looks like we have logging in parts of the logic, but not all. So it seems like the plugin isn't finding the actual file locally. I'm not sure why it would work in staging though.

Is your local file a symbolic link by chance?

**Comment by wjthomas9** [comment]
My public folder is a symbolic link to public_html. I thought that might be
it too, but I tried it without the symbolic link and still couldn't get any
output.

**Comment by erikreagan** [comment]
Strange. If I push out a little more error logging, can you try again and see if we can catch what's going on locally?

**Comment by wjthomas9** [comment]
Happy to.

**Comment by erikreagan** [comment]
[Download the latest here](https://github.com/focuslabllc/craftcms-cachebuster/archive/master.zip) and try it out again locally. I'm assuming it will still not work because all I've done is add some error logging.

Head to the error page (`/admin/utils/logs/cachebuster.log`) for your site and see if you have an error logged with path information.

**Comment by wjthomas9** [comment]
Here's the output...

```
2016/11/16 18:45:02 [error] [plugin] Could not find your asset file (value provided was '/assets/css/pudik.css' and we looked for the file at '/Users/jonthomas/.composer/vendor/laravel/valet/assets/css/pudik.css')
in /Users/jonthomas/Sites/pudik/craft/app/etc/plugins/BasePlugin.php (65)
in /Users/jonthomas/Sites/pudik/craft/plugins/cachebuster/services/CacheBusterService.php (158)
in /Users/jonthomas/Sites/pudik/craft/plugins/cachebuster/services/CacheBusterService.php (35)
2016/11/16 18:45:02 [error] [plugin] Could not find your asset file (value provided was '/assets/js/main.js' and we looked for the file at '/Users/jonthomas/.composer/vendor/laravel/valet/assets/js/main.js')
in /Users/jonthomas/Sites/pudik/craft/app/etc/plugins/BasePlugin.php (65)
in /Users/jonthomas/Sites/pudik/craft/plugins/cachebuster/services/CacheBusterService.php (158)
in /Users/jonthomas/Sites/pudik/craft/plugins/cachebuster/services/CacheBusterService.php (35)

******************************************************************************************************
```

**Comment by wjthomas9** [comment]
Forgot to mention I was using Valet. That's definitely a big difference between local and staging. ;)

**Comment by erikreagan** [comment]
Yup, I just noticed that Valet is affecting the path building here. I've not used it before so I'll need to look into how this can be addressed. I'll report back. :)

**Comment by wjthomas9** [comment]
Ok. Will update the issue title to reflect that it's Valet related. I've noticed some other plugins being affected by Valet as well. Will probably go back to MAMP for the time being.

**Comment by erikreagan** [comment]
> Ok. Will update the issue title to reflect that it's Valet related. I've noticed some other plugins being affected by Valet as well.

Okay cool. Thanks for that.

So in short form, what is Valet _doing_?

**Comment by wjthomas9** [comment]
I'll let Jeffrey Way answer that one for you. :)

https://laracasts.com/lessons/laravel-valet-is-the-bomb

**Comment by wjthomas9** [comment]
FYI, switched back to MAMP and the plugin works fine on local. Just wanted to rule out the localhost thing.

**Comment by erikreagan** [comment]
Man, ain't nobody got time for an 8 minute video right now. :p 

Can you give me the tweet-size text version of what Valet does? Particularly in terms of your environment? If you have an answer that might help. Otherwise I'll go digging when I have a little more time. No worries at all.

**Comment by wjthomas9** [comment]
Hah. In short... automatically allows me to serve every folder in the parent
folder where Valet is parked with a .dev domain, and easily share it with
the world as well with tunneling. No server setup, host file editing etc.
Create a folder, go to folder.dev. Done.

From their website...

"Valet is a Laravel development environment for Mac minimalists. No
Vagrant, No Apache, No Nginx, No /etc/hosts file. You can even share your
sites publicly using local tunnels. Yeah, we like it too.

Laravel Valet configures your Mac to always run Caddy in the background
when your machine starts. Then, using DnsMasq, Valet proxies all requests
on the *.dev domain to point to sites installed on your local machine."

**Comment by erikreagan** [comment]
Thanks for the description there, Jon. I checked out the Valet site and for now think we're safe to just close this issue. If someone else comes across is we might consider adjusting the logic a bit to accommodate dynamic path changes like this. But for now, goodbye. :)

**Comment by wjthomas9** [comment]
Yeah, no problem closing this. Take care!
